### ISSUE TITLE
IoC Autofac setup

### ISSUE THREAD

**Issue by martosource** [kristofferahl/FluentSecurity#88]
I have tried to setup FluentSecurity with Autofac.  

I have got it to a point where is it complaining that it cannot resolve the constructor for SecurityContext.

Is there an example for using FluentSecurity with Autofac?

**Comment by tiesont** [comment]
I'm assuming you followed http://www.fluentsecurity.net/wiki/IoC-container-integration ?

**Comment by trustorm** [comment]
On review Autofac and Common ServiceLocator extensions are throwing an exception as I would like to keep the FluentSecurity defaults.  

Using the following code:
```
config.ResolveServicesUsing(
                    type =>
                    {
                        object obj; 

                        container.TryResolve(type, out obj);

                        return new List<object>{obj};
                    },
                    type =>
                    {
                        object obj;
                        container.TryResolve(type, out obj);

                        return obj;});
```

Not sure if it is the best way, but it is working.

**Comment by kristofferahl** [comment]
@trustorm I haven't used autofac so I can't tell you the best way. However, you do not need to specify the second argument of ResolveServicesUsing as only the first one is required. Also, you should make sure you return an empty list of objects if TryResolve results in null.

**Comment by tiesont** [comment]
Another option, if you've configured a custom DependencyResolver (by calling `System.Web.Mvc.DependencyResolver.SetResolver` in, say, the Global.asax file), is to implement the FluentSecurity.ISecurityServiceLocator interface like so:

```
public class FluentSecurityServiceLocator : ISecurityServiceLocator
{
    public object Resolve(Type typeToResolve)
    {
        return DependencyResolver.Current.GetService(typeToResolve);
    }

    public IEnumerable<object> ResolveAll(Type typeToResolve)
    {
        return DependencyResolver.Current.GetServices(typeToResolve).Cast<object>();
    }
}
```

Then you can override the internal service locator Fluent Security provides as shown in the wiki I linked to previously:
```
SecurityConfigurator.Configure(configuration =>
{
    configuration.ResolveServicesUsing(new FluentSecurityServiceLocator());
});
```
